[package]
name         = "scim-render"
edition.workspace      = true
rust-version.workspace = true
version.workspace      = true
authors.workspace      = true
license.workspace      = true

[dependencies]
scim-store = { path = "../scim-store", version = "0.1.0" }
scim-world = { path = "../scim-world", version = "0.1.0" }
thiserror  = { workspace = true }
wgpu       = { workspace = true }
winit      = { workspace = true }
bytemuck   = { workspace = true }
glam       = { workspace = true }
pollster   = { workspace = true }

[dev-dependencies]
tempfile = "=3.10.1"

[lints]
workspace = true
