[package]
name         = "scim-savefile"
edition.workspace      = true
rust-version.workspace = true
version.workspace      = true
authors.workspace      = true
license.workspace      = true

[dependencies]
thiserror.workspace   = true
serde                 = { workspace = true, features = ["derive"] }
miniz_oxide.workspace = true

[lints]
workspace = true
