[package]
name         = "scim-savefile"
edition.workspace      = true
rust-version.workspace = true
version.workspace      = true
authors.workspace      = true
license.workspace      = true

[dependencies]
thiserror.workspace   = true
serde                 = { workspace = true, features = ["derive"] }
miniz_oxide.workspace = true

[dev-dependencies]
scim-model = { path = "../scim-model", version = "0.1.0" }
scim-store = { path = "../scim-store", version = "0.1.0" }
tempfile   = "=3.10.1"

[lints]
workspace = true
