[package]
name         = "scim-model"
edition.workspace      = true
rust-version.workspace = true
version.workspace      = true
authors.workspace      = true
license.workspace      = true

[dependencies]
scim-savefile = { path = "../scim-savefile" }
serde         = { workspace = true }
thiserror     = { workspace = true }
toml          = { workspace = true }

[lints]
workspace = true
